#!/usr/bin/env php
<?php

class Bow
{
	private final function __construct() {}
	private final function __clone() {}

	/**
	 * Lance Bow.
	 *
	 * @param int $argc
	 * @param array $argv
	 * @return int
	 */
	public static function run($argc, array $argv)
	{
        $status = 0;
		$argc -= 1;
        array_shift($argv);

        if ($argc <= 0) {
            $argv[0] = "help";
        }

        // formate cmd.
        list($cmd, $param)  = explode(":", $argv[0]);

		switch ($cmd) {
			case 'generate':
                $name = null;
				if ($param !== "key") {
                    if (!isset($argv[1])) {
                        return static::usage();
                    }
                    $name = $argv[1];
                }
				switch ($param) {
					case 'model':
						static::createModel($name);
						break;
					case 'controller':
						$status = static::createController($name);
						break;
					case 'middleware':
						$status = static::createMiddleware($name);
						break;
					case 'key':
						$status = static::generateKey();
						break;
					default:
						$status = static::usage();
						break;
				}
				break;

			case 'migrate':
                    $table = null;
                    $date = null;
                    if (!isset($argv[1])) {
                        return static::usage();
                    } else {
                        $table = $argv[1];
                    }
                    if (isset($argv[2])) {
                        if (preg_match("#^[0-9]{4}_[0-9]{2}_[0-9]{2}$#", $argv[2])) {
                            $date = $argv[2];
                        }
                    }
                    switch($param) {
                        case "make":
                            static::createMigration($table);
                            break;
                        case "up":
                            static::migrate($table, $date, "up");
                            break;
                        case "down":
                            static::migrate($table, $date, "down");
                            break;
                        default:
                            return static::usage();
                            break;
                    }

				break;

			case 'help':
				$status = static::usage();
				break;

			case 'server':
				if (isset($argv[1])) {
					$port = (int) $argv[1];
				} else {
					$port = "5000";
				}
                // resource.
				$r = fopen("php://stdout", "w");
				if ($r) {
					fwrite($r, "Web Server start at http://localhost:$port\nCtrl-C for shutdown it\n");
				}
				fclose($r);
                // lancement du serveur.
				shell_exec("php -S localhost:$port server.php");
				break;

			default:
				$status = static::usage();
				break;
		}

		return $status;
	}

    /**
     * @param string $table
     */
    private static function createMigration($table)
    {
        $className = ucfirst($table);
$migrate = <<<doc
<?php

use \Bow\Database\Migration\Schema;
use \Bow\Database\Migration\Blueprint;
use \Bow\Database\Migration\Migration;

class Create{$className}Table extends Migration
{
    /**
     * create {$table} table
     */
    public function up()
    {
        Schema::create("$table", function(Blueprint \$table) {
            // do something
        });
    }

    /**
     * drop a table {$table}
     */
    public function down()
    {
        Schema::drop("$table");
    }
}
doc;
        file_put_contents(__DIR__."/migration/create_{$table}_table_" . date("Y_m_d") . ".php", $migrate);
        echo "\033[0;32mMigration file for $table created.\033[00m\n";
    }

    /**
     * @param string $table le nom de table
     * @param string $date la date de migration qui represente un cle unique pour la migration
     * @param string $type le type de migration up|down
     * @return int
     * @throws ErrorException
     */
    private static function migrate($table, $date, $type)
    {
        $file = __DIR__.strtolower("/migration/create_{$table}_table_{$date}.php");

        if (file_exists($file)) {
            require __DIR__ . "/vendor/autoload.php";
            @include $file;
            $class = "Create".ucfirst($table)."Table";
            call_user_func([new $class, "$type"]);
        } else {
            throw new ErrorException("$file n'existe pas.", E_USER_ERROR);
        }

        return 0;
    }
	/**
	 * @param $middlewareName
	 * @return int
	 */
	private static function createMiddleware($middlewareName)
	{
		$middlewareName = ucfirst($middlewareName);

		if (file_exists(__DIR__ . "/app/Middleware/$middlewareName.php")) {
			echo "\033[0;31mMiddleware <\033[0;33m@\033[0;31m$middlewareName\033[00m\033[0;31m> already exist.\033[00m\n";
			return 0;
		}

$middlewareTemplate = <<<CM
<?php

namespace App\Middleware;

use Bow\Database\Database;

class {$middlewareName}
{
	/**
	 * Fonction de lancement du middleware.
	 *
	 * @param mixed
	 * @return boolean
	 */
	public function handler()
	{
		// do something here
	}
}
CM;
		file_put_contents(__DIR__."/app/Middleware/$middlewareName.php", $middlewareTemplate);
		echo "\033[0;32mMiddleware \033[00m@@{$middlewareName}\033[0;32m Created.\033[00m\n";

		return 0;
	}

	/**
	 * @param $controllerName
	 * @return int
	 */
	private static function createController($controllerName)
	{
		if (!preg_match("/controller$/i", $controllerName)) {
			$controllerName = ucfirst($controllerName) . "Controller";
		} else {
			if (preg_match("/^(.+)(controller)$/", $controllerName, $match)) {
				array_shift($match);
				$controllerName = ucfirst($match[0]) . ucfirst($match[1]);
			} else {
				$controllerName = ucfirst($controllerName);
			}
		}

		if (file_exists("app/Controller/$controllerName.php")) {
			echo "\033[0;31mController <\033[0;33m@\033[0;31m$controllerName\033[00m\033[0;31m> already exist.\033[00m\n";
			return 0;
		}

$controllerTemplate =<<<CC
<?php

namespace App\Controller;

use Exception;
use App\Controller;
use Bow\Database\Database;

class {$controllerName} extends Controller
{
	/**
	 * Start point
	 *
	 * @return mixed
	 */
   	public function index()
   	{
		// do something here.
   	}

	/**
	 * Add information
	 *
	 * @param Response \$res
	 */
   	public function add()
   	{
		// do something here.
	}

	/**
	 * get all information
	 *
	 * @return mixed
	 */
 	public function get()
   	{
		// do something here.
	}

	/**
	 * update method
	 *
	 * @return mixed
	 */
 	public function update()
   	{
		// do something here.
	}

	/**
	 * Delete data
	 *
	 * @return mixed
	 */
   	public function delete()
	{
		// do something here.
 	}
}
CC;

		file_put_contents("app/Controller/$controllerName.php", $controllerTemplate);
		echo "\033[0;32mController \033[00m@@{$controllerName}\033[0;32m have been Create.\033[00m\n";

		return 0;
	}

	/**
	 * @param $modelName
	 * @return int
	 */
	private static function createModel($modelName)
	{
		$tableName = strtolower($modelName);
		$modelName = ucfirst($modelName);

$model = <<<MODEL
<?php

namespace App\Model;

use Bow\Exception\TableException;

class ${modelName}
{
	/**
	 * Facade
	 * @param string \$method
	 * @param array \$arg
	 * @return Table
	 */
	public static function __callStatic(\$method, \$arg)
	{
		\$table = table("${tableName}");
		if (method_exists(\$table, \$method)) {
			return call_user_func_array([\$table, \$method], \$arg);
		} else {
			throw new TableException("method \$method not found", 1);
		}

		return \$table;
	}
}

MODEL;
		if (file_exists("app/Model/${modelName}.php")) {
			echo "\033[0;33mModel <\033[0;33m@\033[0;31m${modelName}\033[00m\033[0;31m> already exist.\033[00m";

            return 0;
		}

		file_put_contents("app/Model/${modelName}.php", $model);

		echo "\033[0;32mModel \033[00m@@${modelName}\033[0;32m Created.\033[00m\n";

		return 0;
	}

	/**
	 * @return int
	 */
	private static function usage()
	{

$usage = <<<USAGE

Bow usage: php bow :command :option :stdout-file-name

\033[0;31mcommand\033[00m:

 \033[0;32mgenerate\033[00m create a user class
  option:
   \033[0;33mgenerate:controller\033[00m 	for create controller
   \033[0;33mgenerate:model\033[00m 	for create model
   \033[0;33mgenerate:middleware\033[00m  for create middleware
   \033[0;33mgenerate:key\033[00m 	for create new app key

 \033[0;32mmigrate\033[00m create migration of user model
  option:
   \033[0;33mmigrate:up\033[00m		Update || create table of the migration
   \033[0;33mmigrate:down\033[00m		To drop migration
   \033[0;33mmigrate:make\033[00m		To create migration

USAGE;
		echo $usage;

		return 0;
	}

	/**
	 * generate key
	 *
	 * @return integer
	 */
	private function generateKey() {
		$key = base64_encode(openssl_random_pseudo_bytes(5) . date('Y-m-d H:i:s'));
		file_put_contents("config/.key", $key);
		echo "appkey: \033[0;32m$key\033[00m\n";

		return 0;
	}
}

try {
	$s = Bow::run($argc, $argv);
} catch (Exception $e) {
	echo "\033[0;31m" . $e->getMessage() . "\033[00m\n";
} finally {
	$s = 1;
}

exit($s);
