[supervisord]
nodaemon=true
user=root
logfile=/app/var/logs/supervisord.log
pidfile=/app/var/supervisord.pid
childlogdir=/app/var/logs
loglevel=info

[program:crond]
command=/usr/sbin/crond -f -l 8
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/app/var/logs/crond.log
stdout_logfile=/app/var/logs/crond.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:frankenphp]
command=/usr/local/bin/frankenphp run --config /etc/caddy/Caddyfile
user=root
autostart=true
autorestart=true
startretries=3
stdout_logfile=/app/var/logs/frankenphp.log
stderr_logfile=/app/var/logs/frankenphp_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
priority=1

[program:beanstalkd]
command=/usr/bin/beanstalkd -l 0.0.0.0 -p 11300
user=root
autostart=true
autorestart=true
startretries=3
stdout_logfile=/app/var/logs/beanstalkd.log
stderr_logfile=/app/var/logs/beanstalkd_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
priority=2

[program:microservice]
directory=/var/www/html
command=php bow microservice:listen
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/var/log/supervisor/microservice_worker.log
stdout_logfile=/var/log/supervisor/microservice_worker.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
