[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
loglevel=info

[program:crond]
command=/usr/sbin/crond -f -l 8
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/var/log/supervisor/crond.log
stdout_logfile=/var/log/supervisor/crond.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:microservice]
directory=/var/www/html
command=php bow microservice:listen
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/var/log/supervisor/microservice_worker.log
stdout_logfile=/var/log/supervisor/microservice_worker.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
